const CartActionsTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEMS: "ADD_ITEMS",
  CLEAR_ITEM: "CLEAR_ITEM",
  REMOVE_ITEM:'REMOVE_ITEM',
  CLEAR_CART:'CLEAR_CART'
};

export default CartActionsTypes;
